import { CartProvider } from '@/helpers/context/CartContext'
import type { Metadata } from 'next'
import { Nunito, Quicksand } from 'next/font/google'
import ClientLayout from './client-layout'
import './globals.css'

const nunitoSans = Nunito({
	variable: '--font-nunito-sans',
	subsets: ['latin'],
})

const quicksandSans = Quicksand({
	variable: '--font-quicksand-sans',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<CartProvider>
			<html lang='en'>
				<body
					className={`${nunitoSans.variable} ${quicksandSans.variable} antialiased`}
				>
					<ClientLayout>{children}</ClientLayout>
				</body>
			</html>
		</CartProvider>
	)
}
