import { CartProvider } from '@/helpers/context/CartContext'
import type { Metadata } from 'next'
import {
	Inter,
	Montserrat,
	Nunito,
	Poppins,
	Quicksand,
	Roboto,
} from 'next/font/google'
import ClientLayout from './client-layout'
import './globals.css'

const nunitoSans = Nunito({
	variable: '--font-nunito-sans',
	subsets: ['latin'],
})

const quicksandSans = Quicksand({
	variable: '--font-quicksand-sans',
	subsets: ['latin'],
})

const poppins = Poppins({
	weight: ['300', '400', '500', '600', '700', '800', '900'],
	style: 'normal',
	subsets: ['latin'],
})

const inter = Inter({
	weight: ['300', '400', '500', '600', '700', '800', '900'],
	style: 'normal',
	subsets: ['latin'],
})

const montserratSans = Montserrat({
	weight: ['300', '400', '500', '600', '700', '800', '900'],
	style: 'normal',
	subsets: ['latin'],
})

const robotoSerif = Roboto({
	weight: ['100', '300', '400', '500', '700', '900'],
	style: 'normal',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<CartProvider>
			<html lang='en'>
				<body
					className={`${nunitoSans.variable} ${quicksandSans.variable} ${montserratSans} ${robotoSerif} ${inter} ${poppins} antialiased`}
				>
					<ClientLayout>{children}</ClientLayout>
				</body>
			</html>
		</CartProvider>
	)
}
